### PR TITLE
Corrected menu selection to Classic Infrastructure

### PR DESCRIPTION
**Pull request by osenbach**
The current menu selection is Classic Infrastructure.  Updated doc to reflect

### CODE REVIEW

**Comment by osenbach** [comment]
@sheltons mind a review?

**Review by sheltons — APPROVED** [review]
👍

**Comment by sheltons** [comment]
@osenbach In the future, could you make sure you're making these changes in the Staging environment? It helps the documentation team keep our repositories in sync.

Thanks for the catch!

**Comment by osenbach** [comment]
@sheltons what is the process to make the change to the Staging environment?

**Pull request merged**
